[workspace]
members = ["crates/a365dt-cli"]
resolver = "3"

[workspace.package]
version = "0.6.2"
edition = "2024"
license = "Apache-2.0"

[workspace.dependencies]
# external dependencies
base64 = "0.22"
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
console = "0.16"
directories = "6"
indicatif = "0.18"
image = { version = "0.25", default-features = false, features = ["jpeg"] }
rapidfuzz = "0.5"
reqwest = { version = "0.13", default-features = false, features = ["json", "query", "rustls"] }
security-framework = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["fs", "io-util", "macros", "process", "rt-multi-thread", "signal", "sync", "time"] }
unicode-normalization = "0.1"

# test dependencies
divan = "0.1"
pretty_assertions = "1"

[profile.dev]
opt-level = "z"
debug = false
strip = "symbols"
lto = true
codegen-units = 1
panic = "abort"

[profile.release]
opt-level = "z"
strip = "symbols"
lto = true
codegen-units = 1
panic = "abort"
